# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'RadioTest' do
    
    use_frameworks!

  # Pods for RadioTest
	pod 'Alamofire', '~> 4.4'
	pod 'Kanna', '~> 2.1.0’

end
